services:
  - type: web
    name: synthetic-data-generator-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true